services:
  api:
    build: .
    container_name: innovatech-api
    ports:
      - "5040:5040"
    environment:
      - NODE_ENV=production
      - SERVER_PORT=5040
      - DB_NAME=ba5y5n8oyxxeexbybziu
      - DB_HOST=ba5y5n8oyxxeexbybziu-mysql.services.clever-cloud.com
      - DB_USER=uf1lw7xxtlsrtze8
      - DB_PASSWORD=IIEnygccnY3sIaPnXQQU
      - DB_PORT=3306
      - JWT_SECRET=1033827371
      - EMAIL_USER=innovatechdynamic@gmail.com
      - EMAIL_PASS=xbpjvzilqgwrjbmw
    restart: unless-stopped
    networks:
      - innovatech-network

networks:
  innovatech-network:
    driver: bridge
